### ISSUE TITLE
Support for SQL Server 2014

### ISSUE THREAD

**Issue by NickWright25** [PawelGerr/Thinktecture.EntityFrameworkCore#19]
I'm trying to use temporary tables with a connection to a database server running SQL Server 2014. 
Unfortunately, there seems to be DROP TABLE IF EXISTS SQL query only supported by SQL Server 2016 and up. 

It's caused the following error:
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IF'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

Are there any plans to support previous versions of SQL Server?

**Comment by poizan42** [comment]
What a funny coincidence that someone else reported this issue just now when I ran into it yesterday. I have created a PR since the fix is quite trivial (the pre-2016 compatible sql is already used elsewhere in the project).

**Comment by PawelGerr** [comment]
Fix is released with v4.2.1

Please note, that some features, like [Collection Parameters](https://dev.azure.com/pawelgerr/Thinktecture.EntityFrameworkCore/_wiki/wikis/Thinktecture.EntityFrameworkCore.wiki/109/Collection-Parameters-(temp-tables-light)), are still not supported in older versions of SQL Server.

**Comment by PawelGerr** [comment]
4.2.2 released
